### ISSUE TITLE
a_priori.py

### ISSUE THREAD

**Issue by Nwntastaliadouros** [dmst-algorithms-course/assignment-2015-3#1]
import re
import unittest
from collections import defaultdict
import itertools
import csv
import sys
import getopt

def load_dataset(infile,n):
    "Load the sample dataset."
    mylist = []
    input_file = open(infile, 'r')
    csv_reader = csv.reader(input_file, delimiter=',')
    for row in csv_reader:

```
    if n==0:
        lc_stripped_items = [field.strip().lower() for field in row]

        mylist.append(lc_stripped_items)
    else:
        stripped_items = [field.strip() for field in row]
        mylist.append(stripped_items)
input_file.close()
mytuple = tuple(mylist)
return mytuple
```

def createC1(dataset):
    "Create a list of candidate item sets of size one."
    c1 = []
    for transaction in dataset:
        for item in transaction:
            if not [item] in c1:
                c1.append([item])
    c1.sort()

```
return list(map(frozenset, c1))
```

def scanD(dataset, candidates, min_support,p):
    "Returns all candidates that meets a minimum support level"
    sscnt = {}
    for tid in dataset:
        for can in candidates:
            if can.issubset(tid):
                sscnt.setdefault(can, 0)
                sscnt[can] += 1

```
num_items = float(len(dataset))
retlist = []
support_data = {}
if p == 1:
    min_support=min_support/100
for key in sscnt:
    if p == 1:
        support = sscnt[key]/num_items
    else:
        support = sscnt[key]

    if support >= min_support:

        retlist.insert(0, key)
        support_data[key] = support
return retlist, support_data
```

def aprioriGen(freq_sets, k):
    "Generate the joint transactions from candidate sets"
    retList = []
    lenLk = len(freq_sets)
    for i in range(lenLk):
        for j in range(i + 1, lenLk):
            L1 = list(freq_sets[i])[:k - 2]
            L2 = list(freq_sets[j])[:k - 2]
            L1.sort()
            L2.sort()
            if L1 == L2:
                retList.append(freq_sets[i] | freq_sets[j])
    return retList

def apriori(dataset, minsupport,p):
    "Generate a list of candidate item sets"
    C1 = createC1(dataset)
    D = list(map(set, dataset))
    L1, support_data = scanD(D, C1, minsupport,p)
    L = [L1]
    k = 2
    while (len(L[k - 2]) > 0):
        Ck = aprioriGen(L[k - 2], k)
        Lk, supK = scanD(D, Ck, minsupport,p)
        support_data.update(supK)
        L.append(Lk)
        k += 1

```
return L, support_data
```

if **name** == '**main**':

```
if  (len(sys.argv) != 3 and len(sys.argv) != 4 and len(sys.argv) != 5 and len(sys.argv) != 7 and len(sys.argv) != 6):
    sys.exit("usage:python a_priori.py [-n] [-p] [-o OUTPUT] support filename")
inputfile = 'none'
outputfile = 'none'
n=0
p=0
sup=-1
flag=0  
for arg in sys.argv[1:]:

    if flag==1:
        outputfile = arg
        flag=0
        continue
    if arg == '-n':
        n=1
    elif arg == '-p':
        p=1
    elif arg == '-o':
        flag=1
        continue
    elif sup == -1:
        sup = arg
    else:
        inputfile = str(arg)
if sup==-1 or inputfile=='none':
    sys.exit("No support or inputfile!usage:python a_priori.py [-n] [-p] [-o OUTPUT] support filename")


dataset=load_dataset(inputfile,int(n))
L=apriori(dataset,int(sup),int(p))

if outputfile == 'none':
    for v in L[1:]:
        print ('Results are:')
        print(v)
else:
    output_file = open(outputfile, 'w')
    csv_writer = csv.writer(output_file, delimiter=';')
    for freqs in L[1:]:
        row = []
        for key in sorted(freqs.keys()):
            row.append("{0}:{1}".format(key, freqs[key]))
        csv_writer.writerow(row)
```

**Comment by louridas** [comment]
Η εργασία δεν υποβάλλεται μέσω issue στο GitHub!
